### ISSUE TITLE
Pretty URLs shipped standard

### ISSUE THREAD

**Issue by zwhitchcox** [linnovate/mean#1027]
I slightly modified the mean package, as you can see [here](https://github.com/zwhitchcox/mean/tree/pretty-urls) to remove the #! prefix. I'm just trying to get a feel if anyone thinks this should be included in the standard package.

The key change is right [here](https://github.com/zwhitchcox/mean/blob/pretty-urls/config/express.js#L116). Instead of excluding every possible path not needed, as suggested in [this article](http://blog.inzite.io/how-to-remove-hashbang-for-single-page-meanio-web-app/), which, I think results in much simpler, cleaner, easier to use code, but, of course, I could be wrong.

You can see an example of how to include a path in the [articles package](https://github.com/zwhitchcox/mean/blob/pretty-urls/packages/articles/server/routes/articles.js#L14)

You can download this and use it right now, and everything should work. Please let me know what you think! If there is interest, I will submit a pull request. You'll have to checkout the pretty-urls branch

**Comment by liorkesos** [comment]
Hey @zwihtchcox - this subject is very interesting.
The main thing that we need to understand is the impact on seo.
The #! is used by google to undertand the routing of the site and we need
to understand how this would work without it.
The best solution was if this could be an optional "init question" or a
packagr somehow altering the configuration and code needed to enable or
disable this until we have a feel of what this means from an seo
perspective.
Lior

On Thu, Jan 22, 2015 at 9:52 PM, zwhitchcox <notifications@github.com>
wrote:

> I slightly modified the mean package, as you can see here
> <https://github.com/zwhitchcox/mean/tree/pretty-urls> to remove the #!
> prefix. I'm just trying to get a feel if anyone thinks this should be
> included in the standard package.
>
> The key change is right here
> <https://github.com/zwhitchcox/mean/blob/pretty-urls/config/express.js#L116>.
> Instead of excluding every possible path not needed, as suggested in this
> article
> <http://blog.inzite.io/how-to-remove-hashbang-for-single-page-meanio-web-app/>,
> which, I think results in much simpler, cleaner, easier to use code, but,
> of course, I could be wrong.
>
> You can see an example of how to include a path in the articles package
> <https://github.com/zwhitchcox/mean/blob/pretty-urls/packages/articles/server/routes/articles.js#L14>
>
> You can download this and use it right now, and everything should work.
> Please let me know what you think! If there is interest, I will submit a
> pull request. You'll have to checkout the pretty-urls branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1027>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by enkodellc** [comment]
@zwhitchcox  After reading the blog article you posted http://blog.inzite.io/how-to-remove-hashbang-for-single-page-meanio-web-app/ I am definitely changing the server routes to use the /api  I have ran into some debugging issues in the past because they were not clearly defined. I truly believe that change would be SUPER beneficial to new developers to the MEAN stack.

**Comment by liorkesos** [comment]
Hey guys.
This is an interesting bit about html5push state SEO
https://prerender.io/js-seo/angularjs-seo-get-your-site-indexed-and-to-the-top-of-the-search-results/

I think we should adapt html5push state (with /api as express route
namespace).
And make sure we return the html (using phantom.js? ) when querying
/whatever-url?_escaped_fragment_=


On Sat, Jan 24, 2015 at 11:30 PM, Keith <notifications@github.com> wrote:

> @zwhitchcox <https://github.com/zwhitchcox> After reading the blog
> article you posted
> http://blog.inzite.io/how-to-remove-hashbang-for-single-page-meanio-web-app/
> I am definitely changing the server routes to use the /api I have ran into
> some debugging issues in the past because they were not clearly defined. I
> truly believe that change would be SUPER beneficial to new developers to
> the MEAN stack.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1027#issuecomment-71338263>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by liorkesos** [comment]
I think we can use or fork the mean-seo npm as a dependency it deals with creating the page on the server side.
https://github.com/meanjs/mean-seo
@zwhitchcox || @enkodellc I would defently consider mergin a PR if you prepare one and will probably integrate this as part of the upcoming 0.5 release.
Great job.

**Comment by MilosStanic** [comment]
+1 for /api/* routes

**Comment by zwhitchcox** [comment]
In [this article](https://developers.google.com/webmasters/ajax-crawling/docs/specification), Google suggests, you can just add
```HTML
<meta name="fragment" content="!">
```
to the top of your page, and it will be crawled as though it had a hash bang prefix. Could it be as simple as adding this to the top of the page?

**Comment by zwhitchcox** [comment]
Well, I basically just did what we said. All the urls are pretty, and if you go to
```
localhost:3000:?_escaped_fragment_=articles
```
it returns an html rendered version of the page to ensure good seo.

Also, I fixed it where it automatically updates when you delete an article on the article page.


Please tell me what ya'll think. I'd be happy to implement any changes you see, or if you want to to do a pull request, that would be fine too. Just want to make sure I'm not missing anything before I do a pull request.

**Comment by pratik60** [comment]
@enkodellc - Nice link you shared....Changed all the services and factories in the entire app, and made them point to the /api/ routes.

Now only jwt tokens and pathauto left when it comes to url handling :-)

**Comment by pratik60** [comment]
@enkodellc @zwhitchcox 

Hey, the route 

http://localhost:3000/articles => redirects me to http://localhost:3000/articles/ => And this doesn't work

http://localhost:3000/articles/create, http://localhost:3000/articles/54c883f576031ded2c3e7997 all work fine.

If I change my first route to http://localhost:3000/articles/all instead in articles/public/routes/articles.js that works as well. Any idea why?

**Comment by enkodellc** [comment]
I have the prettyurl's rewritten in my app with the help of a dev that is working with me on my project. We implemented connect-modrewrite and changed all the paths... works really well. I don't know if I will have time to create a PR..

Here are some snippets that might help:

express.js
```
modRewrite = require('connect-modrewrite');

  app.use(modRewrite([
    '!^/api/.*|\\.html|\\.js|\\.css|\\.swf|\\.jp(e?)g|\\.png|\\.gif|\\.svg|\\.eot|\\.ttf|\\.woff|\\.pdf$ /index.html [L]'
  ]));
```

changed all $resource paths to start with '/api/*

system.js
```
angular.module('mean.system')
  .config(['$locationProvider', '$stateProvider', '$urlRouterProvider',
    function ($locationProvider, $stateProvider, $urlRouterProvider) {
      $locationProvider.html5Mode({
        enabled: true,
        requireBase: false
      });
```
server routes index.js
```
'use strict';

var mean = require('meanio');

module.exports = function(System, app, auth, database) {

// Home route
  var index = require('../controllers/index');

  app.route('*')
    .get(function(req, res, next) {
      var packages = [];
      for (var name in mean.modules) {
        packages.push(req.url.indexOf(name + '/views') === -1);
        packages.push(req.url.indexOf(name + '/assets') === -1);
      }
      var api = req.url.indexOf('/api') === -1,
        modules = req.url.indexOf('modules') === -1,
        packageRoutes = packages.indexOf(false) === -1,
        local = req.url.indexOf('auth/login') === -1,
        linkedin = req.url.indexOf('auth/linkedin') === -1,
        facebook = req.url.indexOf('auth/facebook') === -1;

      // If request is not API
      // Render index.html and pass further routing to AngularJS
      // Otherwise pass request to the server
      if (api && modules && packageRoutes && linkedin && facebook && local) {
        index.render(req, res, next);
      } else {

        next();
      }
    });
};
```

add base to head.html
```
<base href="/">
```

That seemed to be about it. No time to create a PR right now as I have a list of several other MEAN updates we are in the process of cleaning up.

**Comment by pratik60** [comment]
No PR required, for now :-)

I have got 98% of it working....But two links are a problem /articles which should list all articles and /logout. 

Just confirm this for me =>  After pretty urls, I don’t think the link /logout will also work for you when you have it within a href in your angular app. Explicitly going to link works, but otherwise it won’t. Its like angular doesn't recognize the link, so doesn't do anything. 

Can you confirm?

Also for unmatched routes, what do you do?

Currently like this ....

```
angular.module('mean.system').config(['$meanStateProvider', '$urlRouterProvider',
  function($meanStateProvider, $urlRouterProvider) {
    // For unmatched routes:
    $urlRouterProvider.otherwise('/');
```

**Comment by enkodellc** [comment]
I have a dashboard so my unmatched routes I take them to the dashboard state, 
```
$urlRouterProvider.otherwise('dashboard');
```
in that state if they are not logged in it takes them to the landing page.

For logout button the /logout works
```
<a href="/logout" ...
```
user server route
```
  app.route('/logout')
    .get(users.signout);
```

user controller
```
/**
 * Logout
 */
exports.signout = function(req, res) {
  req.logout();
  res.redirect('/');
};
```

**Comment by pratik60** [comment]
@enkodellc - Weird fix for me

              <a href="/logout">
                Logout
              </a>
              <a target="_self" href="/logout">Log Out</a>

**Comment by zwhitchcox** [comment]
@pratik60 Did you change the $resource request for articles to api? you need to change that in articles/public/services/articles.js and in articles/server/routes/articles.js

**Comment by zwhitchcox** [comment]
You guys are geniuses! I love this solution much better.

@pratik60 Did you change the $resource to api in articles/public/services and articles/server/routes?

**Comment by pratik60** [comment]
@zwhitchcox - I even replaced the article package entirely with the your mean, but didn't work. But seemed trivial as only /articles is not working, must be using that route somewhere else or something. There are one or two things which required fixing on your code before you can send a pr.

```
  app.route('/auth/facebook/callback')
    .get(passport.authenticate('facebook', {
      failureRedirect: '/login'
    }), users.authCallback);

  // Setting the github oauth routes
  app.route('/auth/github')
    .get(passport.authenticate('github', {
      failureRedirect: '/login'
    }), users.signin);

```

The failure redirect link here.

Please make sure you run grunt, and test cases before you send the pr.

Also  app.route('/auth/login').get(app.toIndex) //Should this be a part of the core, isn't this something related to mean seo package?

**Comment by zwhitchcox** [comment]
Sorry, hang on, yeah, something got broken...working on it now

**Comment by zwhitchcox** [comment]
Ok, everything should be working now...including the articles package and the facebook login. I tested it and everything :)

Please let me know if you try it out and it work or doesn't work.

**Comment by pratik60** [comment]
@zwhitchcox  => One thing that wasn't working was the menus....Can you check that?

On adding items to a menu, it wasn't showing on the homepage bar initially. Send a pr if you are sure... I'm sure it will be merged soon :-)

**Comment by enkodellc** [comment]
@pratik60... I am getting a login loop and my logout is not working now... Made some other updates last night.  @zwhitchcox  I couldn't find your prettyURL branch to double check you server side / client side route. I am confident that it is in the server side redirect / client side "checkLoggedIn" function. No time to look at it till tonight though.

**Comment by zwhitchcox** [comment]
Thank you so much for your feedback, guys.

Sorry for the radio silence, but I wanted to make sure everything was working properly. I've tested it  pretty exhaustively this time, and I'm almost 100% sure everything is working.

Of course, then, again, we're all human.

Specifically, @pratik60 I was unable to replicate your issue exactly, but I think what was causing the problem was the "::" before the menus in ngRepeat. When I took that out, menus were updating properly. It was the same problem that caused articles not to work.

@enkodellc I've merged the seo/pretty-url branch into my master branch now. It's ready to send a pull request!

That being said, I'm not going to send a pull request until everyone who wants to has had a chance to test it, so I'll wait until probably tomorrow around 9:00PM UTC.

Please don't hesitate to give feedback!

Thanks again

**Comment by pratik60** [comment]
@zwhitchcox - We just updated mean to 4.3 today which has some big changes. You might have to fix a few merge conflicts before you can update the code.

After the merge conflicts are resolved, send a pr, it will be easier to comment there.

**Comment by liorkesos** [comment]
Hey guys - awesome job here!
This is one of the three main features I want to integrate for mean-0.5
Rock on!

On Thu, Jan 29, 2015 at 11:06 PM, Pratik Bothra <notifications@github.com>
wrote:

> @zwhitchcox <https://github.com/zwhitchcox> - We just updated mean to 4.3
> today which has some big changes. You might have to fix a few merge
> conflicts before you can update the code.
>
> After the merge conflicts are resolved, send a pr, it will be easier to
> comment there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1027#issuecomment-72104017>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by zwhitchcox** [comment]
@liorkesos Glad to help :)

@pratik60 in the new version, init.js is deleted, and that's what my version was using to start the whole app...I think I fixed all the other conflicts, but I'm getting these errors when I try to run grunt

```shell
 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.articlesangular.js:38 (anonymous function)angular.js:1764 (anonymous function)angular.js:1688 aangular.js:1762 F.bootstraparticles.js:3 (anonymous function)
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.articlesangular.js:38 (anonymous function)angular.js:1764 (anonymous function)angular.js:1688 aangular.js:1762 F.bootstraparticles.js:4 (anonymous function)
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.articles
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.theme
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.theme
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.theme
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.users
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.users
angular.js:38 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.3.2/$injector/nomod?p0=mean.users
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.2/$injector/modulerr?p0=mean&p1=Error%3A%20…000%2Fbower_components%2Fangular%2Fangular.min.js%3Fhdxfc5cow29%3A17%3A381)
```

**Comment by pratik60** [comment]
Do npm prune, npm install and then bower install

Should fix it.

**Comment by zwhitchcox** [comment]
@pratik60 Nope, still having the same problem...

It's this code 

```js

modRewrite = require('connect-modrewrite')

  app.use(modRewrite([
    '!^/api/.*|\\.html|\\.js|\\.css|\\.swf|\\.jp(e?)g|\\.png|\\.gif|\\.svg|\\.eot|\\.ttf|\\.woff|\\.pdf$ / [L]'
  ]));
```

that's breaking it, but I'm having trouble figuring out why..guess I'm going to have to debug it

**Comment by zwhitchcox** [comment]
Ok, it's working, but it will require changing the new bower web-bootstrap script to include /api/_getModules instead of just /_getModules

It will also include changing the core (the express route) to app.('/api/_getModules').

Another way I could do it is to rewrite my code to

```js
app.use(modRewrite([
    '!^_getModules|/api/.*|\\.html|\\.js|\\.css|\\.swf|\\.jp(e?)g|\\.png|\\.gif|\\.svg|\\.eot|\\.ttf|\\.woff|\\.pdf$ / [L]'
  ]));
```

or something like that, but I think we're implementing best practices, it would make sense to have all api calls include /api/*

for now, though, I'll just do a pull request for the latter change just to make things simpler for now.

Does that sound good?

**Comment by zwhitchcox** [comment]
By the way, @liorkesos what were the other changes you wanted to implement by 0.5?

**Comment by liorkesos** [comment]
The roadmap is here.
I'm sure that more stuff from the community might sneak in.
The current additional features are..
1. Angular best practice adoption (stuff from John papa's angular style
guide)
2. Swagger support
3. Multi dB support first db example, postgres? Redis?

Feel free to discuss in the roadmap trello itself..
Lior

**Comment by VikramTiwari** [comment]
This feature is present in the current branch. Thanks everyone for their continued support.
